### ISSUE TITLE
Permission denied: '/home/kiru'`

### ISSUE THREAD

**Issue by lh641446825** [kirumang/Pix2Pose#1]
Hello,  can you tell me where to download the weights file “inference.hdf5” and “weight_detection” ，I only found  “Base archive”, “Object models”, “Synt. training images”, “All test images” from BOP: Benchmark for 6D Object Pose Estimation. There are only “models”and “model_eval” folders inside，no “models_xyz” folder.
And when I execute the script:`python3 tools/5_evaluation_bop_basic.py <gpu_id> <cfg_path> <dataset_name>`
 I get this error:
`Traceback (most recent call last):
  File "/home/Workspace/Project/Pix2Pose/tools/5_evaluation_bop_basic.py", line 119, in <module>
    os.makedirs(output_img)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/kiru'`
I found no “kiru” in the “os.py”, and I change all paths in the folder “tools” with "kiru". But it doesn't work.
Can you tell me how to solve it? Thank you!

**Comment by kirumang** [comment]
Hello.
1. links to the trained weights are at the bottom of the readme.md in this repository.  
[Repository home](https://github.com/kirumang/Pix2Pose)
There will be a models_xyz folder Inside zip files. and you have to extract them in the same folder for the dataset where you have 'models', 'model_eval'  folders.

2. You don't have to change your own directories to evaluate them. You can change [cfg/cfg_bop2019.json](https://github.com/kirumang/Pix2Pose/blob/master/cfg/cfg_bop2019.json) file properly with respect to your environment. 
I think the reason you have the permission error is you don't have proper permission to create a folder at /home/. I would recommend placing codes and bop datasets in directories where you have proper permissions to read and modify files and set the cfg_bop2019.json file properly.

**Comment by lh641446825** [comment]
Thanks for your reply. I changed "cfg_tless_paper.json" file, now I can evaluate them. But I can't download the weights file, because of it‘s unable to open goole drive link in China. I am trying to solve it. Thanks again.

**Comment by lh641446825** [comment]
Hello, I have trouble, can you tell me where to download the `resnet50_tless_19_inf.h5` file?
