### ISSUE TITLE
Where to download the weight of LINEMOD？

### ISSUE THREAD

**Issue by Sunweijun333** [kirumang/Pix2Pose#10]
Where to download the weight of LINEMOD？

**Comment by kirumang** [comment]
Due to the several updates of my code, the old weights (for LM and LM-O) are not compatible with it. We are working on it and will be available as soon as we re-train them for the next BOP challenge.

**Comment by HamilkarBrq** [comment]
Hey Kiru,
I ran into an issue trying to use the Mask-RCNN weights you uploaded for the LM-O dataset in the ros_pix2pose.py script. The layers "mrcnn_class_logits", "mrcnn_bbox_fc" and "mrcnn_mask" produce this or similar errors.
`Traceback (most recent call last):
  File "ros_pix2pose.py", line 405, in <module>
    r= pix2pose(cfg)
  File "ros_pix2pose.py", line 101, in __init__
    self.detection_model.load_weights(cfg['path_to_detection_weights'], by_name=True)
  File "/home/jsch//Mask_RCNN/mrcnn/model.py", line 2130, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/home/jsch/.venvs/pix2pose/lib64/python3.6/site-packages/keras/engine/saving.py", line 1149, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 64) dtype=float32_ref> has shape (1024, 64), but the saved weight has shape (1024, 36).
`
it is possible to run the code by adding the "exclude" flag in the `MaskRCNN.load_weights` function, but the detections are (obviously) not satisfying.
Could you provide some weights that work out of the box?
Thanks in advance.

**Comment by kirumang** [comment]
Hi,

it seems the weight file is for the LM-O (with 8 classes) while the model is set for LM (with 15 classes). Please check if you set the n_objs, obj labels, and other parameters in the ros_config.json correctly

**Comment by HamilkarBrq** [comment]
Your hint solved the issue. Thanks
