### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by ZrrrKIT** [kirumang/Pix2Pose#13]
Hello,

I am trying to reach the inference time from the paper with RCNN (6-7fps) but it seems there is a bottleneck in pose estimation with the method ``est_pose(...)`` in ``recognition.py``. 

I measure the time it takes to execute certain code segments during the evaluation. It seems the bottleneck lies in the RANSAC computation in the following lines: https://github.com/kirumang/Pix2Pose/blob/843effe0097e9982f4b07dd90b04ede2b9ee9294/pix2pose_model/recognition.py#L128-L168

I used timeit to see how much time it takes for this patch of code to execute and achieve a mean time of around **1 second** pro image. 

I am using 640x400 RGB images, and the **basic_evaluation** script. My GPU is NVIDIA RTX 2070, so I guess the hardware might not be the issue.

What could be the cause for the bottleneck in this case? I achieve the same results for the detections with the Faster R-CNN (130 ms) as the paper, but the pose estimation is significantly worse.

**Comment by kirumang** [comment]
Hello, 
The inference time in the paper is measured using the LineMOD dataset where one target object has to be estimated per scene (a.k.a single object scenario or SiSo task) . The computational time should increase proportionally with respect to the number of target objects in the scene. In addition, the single outlier threshold is used for each object in the paper as described below in README.md file. 
> Important Note Differ from the paper, we used multiple outlier thresholds in the second stage for the BOP challenge since it is not allowed to have different parameters for each object or each dataset. This can be done easily by setting the "outlier_th" in a 1D-array (refer to cfg_bop2019.json). In this setup, the best result, which has the largest inlier points, will be derived during estimation after applying all values in the second stage. To reproduce the results in the paper with fixed outlier threshold values, a 2D-array should be given as in "cfg_tless_paper.json"

Also, the code for the bop challenge proposes multiple candidates per target ("cand_factor" controls the maximum number of candidates). Thus, the time measured in the paper could be reproduced for scenes with a single target object and an outlier threshold value. 
You could try TUD-L or RU-APC datasets to check the running time using our pre-trained weights (all scenes have one target per scene like LineMOD).
In this case, cfg_bop2019.json file has to be changed to:
```
1.  "outlier_th":[0.15,0.25,0.35] 
      -  [0.1 ~ 0.3]: single outlier threshold for all objects
      -  [[0.1], [0.1],[0.2] ... ]: individual outlier threshold for each objects
2. "cand_factor": 2 -> 0
3. "score_type": 2 -> 1
4. "task_type": 2 -> 1
```

**Comment by ZrrrKIT** [comment]
Thank you very much for the quick response!

I am using a custom dataset, with a single object, so this is why I was asking about the time complexity.

Adjusting these parameters solved the problem for me. Now I also have ~6-7 FPS, so the model is viable for real-time applications.

Best regards
