### ISSUE TITLE
Could you release some dataset you genetated?

### ISSUE THREAD

**Issue by ghoshaw** [kirumang/Pix2Pose#14]
Hi, Could you release some data you used in pix2pose?  I want to test some idea but the data generating is complicated,  just few object is ok.  The data is a pair of RGB and XYZ map.
Thank you!

**Comment by ghoshaw** [comment]
Hi, thanks very much, Two objects is enough.


| |
ghoshaw
|
|
ghoshaw@163.com
|
签名由网易邮箱大师定制


On 08/21/2020 21:08，Kiru Park<notifications@github.com> wrote：

Hi, sure. I will share a link with you when I get back to my office next week.
Since the number of objects for the IC-BIN dataset is the smallest, I will give you pairs of RGB and XYZ images for the two objects in the dataset that I have used for the recent BOP challenge (The new PBR images are used in this case).
Is this okay with you? please let me know if you need anything else for your idea.

Thanks!

**Comment by kirumang** [comment]
This is the [link](https://drive.google.com/file/d/1B-BcpTDWCos6mb4XHxfb-ukT8zIQjkL6/view?usp=sharing) to the data.
Please let me know when you successfully download it. I will remove it after you download it since the file is too big.

**Comment by ghoshaw** [comment]
Thanks very much! 
You can remove it. 
And sorry to trouble you again, I find I only have the cat model in the linemod dataset, so in order to test the object detection in real environment,  Could you share the cat dataset?  Thanks  again!

**Comment by kirumang** [comment]
What do you need exactly? do you need "train_xyz" files as I provided for the TUD-L dataset?, or do you need trained weights (detection+pix2pose model) of the cat (object-06 in the BOP format)? 
For the second (trained weights), it is already available on the main page. The weights are trained only on PBR training images.

**Comment by ghoshaw** [comment]
Sorry, I need the train_xyz files.

**Comment by kirumang** [comment]
This is the [link](https://drive.google.com/file/d/17EioxhDNYk4x8qVa_6zSvXL3w8tN2a70/view?usp=sharing) again.
Files are train pairs of cat (obj-06 in LM-O or LM dataset in the bop format) created by [PBR synthetic images](http://ptak.felk.cvut.cz/6DB/public/bop_datasets/lm_train_pbr.zip)

**Comment by ghoshaw** [comment]
Thanks very much, you can remove the new data.
That is all I need for now, and I will close this issue.
