### ISSUE TITLE
pyglet.window.NoSuchConfigException

### ISSUE THREAD

**Issue by lh641446825** [kirumang/Pix2Pose#3]
Hello Kiru,
  I have two problems.
  First, when I used `cfg_bop2019.json` to run `5_evaluation_bop_basic.py`, the following problems occurred:
```
Warning.. have to adjust the scale
Traceback (most recent call last):
  File "/home/Pix2Pose/tools/5_evaluation_bop_basic.py", line 297, in <module>
    img_pred,mask_pred,rot_pred,tra_pred,frac_inlier,bbox_t = obj_pix2pose[obj_order_id].est_pose(image_t,roi.astype(np.int))
ValueError: not enough values to unpack (expected 6, got 5)
```
I changed the values before the equal sign to five on line 297, then get the following information:
`ValueError: too many values to unpack (expected 5)`

Second, when I run `5_evaluation_bop_icp3d.py`, the following problems occurred:
```
if models are not fully listed above, please make sure there are ply files available
Traceback (most recent call last):
  File "/home/Pix2Pose/tools/5_evaluation_bop_icp3d.py", line 193, in <module>
    ren = Renderer((im_width,im_height),cam_K)
  File "/home/Pix2Pose/rendering/renderer_xyz.py", line 96, in get_instance
    instances[cls] = cls(size, cam)
  File "/home/Pix2Pose/rendering/renderer_xyz.py", line 106, in __init__
    app.Canvas.__init__(self, show=False, size=size)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/vispy/app/backends/_pyglet.py", line 211, in __init__
    screen=self._vispy_screen)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/pyglet/window/__init__.py", line 593, in __init__
    config = screen.get_best_config(config)
  File "/home/anaconda3/envs/pix2pose/lib/python3.6/site-packages/pyglet/canvas/base.py", line 197, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```
Can you help me to solve it?

**Comment by kirumang** [comment]
Hi, Hao
Thank you for letting me know. I fixed the first problem with this commit.
de54f5f10b5f4036af698caa2542d35adac0d267

For the second one, the problem is related to pyglet.
It would be possibly caused when you are working in an environment that does not have any actual display. In my case, I solved the issue with xvfb by assigning a virtual display.
`apt-get install xvfb`
`xvfb-run -s "-screen 0 1400x900x24" python3 5_evaluation_bop_icp3d.py`
I hope this can solve your problem.

**Comment by lh641446825** [comment]
I am testing tless, I want to test linemod, but I don't find the corresponding 2D Mask R-CNN Detection + Pix2Pose weights.
I encountered `ValueError after modifying the code: operands could not be broadcast together with shapes (960, 1280) (540,720)`. Seeing that you modified `5_evaluation_bop_basic.py`, it can now run successfully.
I am fixing the second question, I will tell you if there is progress.

**Comment by kirumang** [comment]
Good to know. 
FYI, the rendering pipeline did not work properly in one of my docker containers before. Thus, I am going to implement a better rendering pipeline that is not depending on OpenGL soon.

**Comment by lh641446825** [comment]
After the test, I got `F tensorflow/core/common_runtime/bfc_allocator.cc:384] Check failed: h != kInvalidChunkHandle`.Is this the same when you test it?
Best wish.

**Comment by kirumang** [comment]
Nope, I tested using the current code with T-Less, and there was no error afterward. 
I think it is related to the management of the GPU memory in Tensorflow. 
https://github.com/tensorflow/tensorflow/issues/25474

**Comment by lh641446825** [comment]
Ok, thank you very much!

**Comment by kirumang** [comment]
Did you solve the second problem as well?

**Comment by lh641446825** [comment]
When I tested again,  the following problems occurred:
```
Recognizing scene_id:13, im_id:441
Warning.. have to adjust the scale
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
or
```
Recognizing scene_id:11, im_id:421
Warning.. have to adjust the scale
2019-11-23 09:50:14.647137: F tensorflow/core/common_runtime/bfc_allocator.cc:462] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum) 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
I guess the GPU is overflowing, but it always runs less than 9000M, and GPU total memory is 11.90GiB. Is this the same when you run it?

The second problem, I used `xvfb-run -s "-screen 0 1400x900x24" python3 5_evaluation_bop_icp3d.py 1 /home/Pix2Pose/cfg/cfg_tless_paper.json tless
`, then got `xvfb-run: error: Xvfb failed to start`. 
I will continue to solve it.

**Comment by lh641446825** [comment]
The second problem is solved, thanks.

**Comment by lh641446825** [comment]
The second problem is solved, thanks. And I forget to tell you `5_evaluation_bop_icp3d.py` also need to be fixed, it's same to  `5_evaluation_bop_basic.py`, from line 117.

**Comment by kirumang** [comment]
Thank you. Good to know, I fixed the script as well.
c4a25d809c0c93f492d0fc7afed60886b0b8cff6

**Comment by lh641446825** [comment]
Sorry to bother you again, I used the fixed file, and get the following message:
`Loading obj_000030.ply with vertex colors
Recognizing scene_id:1, im_id:1
INFO: Not setting value for variable vec3 u_light_eye_pos; uniform is not active.
INFO: Not setting value for variable float u_light_ambient_w; uniform is not active.
INFO: Not setting value for variable mat4 u_mv; uniform is not active.
Traceback (most recent call last):
  File "/home/Pix2Pose/tools/5_evaluation_bop_icp3d.py", line 427, in <module>
    diff_mask = np.abs(depth_ref[union_mask]-depth_t[union_mask])<0.02
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1024 but corresponding boolean dimension is 540
`

**Comment by kirumang** [comment]
You have to modify the camera.json file to have the proper size of input images. For Tless,
"height" should be adjusted to 540, and set "width" to 720.
I am not sure where the 1280x1024 resolution comes from.

**Comment by lh641446825** [comment]
Thank you, it works. The figure in my camera.json file is  "height": 1024,  "width": 1280.
