### ISSUE TITLE
Where can I get the weight file trained on TLess?

### ISSUE THREAD

**Issue by GraceJary** [kirumang/Pix2Pose#4]
Thank you for the detail description about this good project. I want to test the evaluation file , however, I don't know where to download the weight file.

**Comment by kirumang** [comment]
Hello, 
Links to the weights are at the bottom of the project description.

**Comment by cucumberbatc** [comment]
@kirumang Hi where can I download resnet50_tless_19_inf.h5? There is no such file on your link.
