### ISSUE TITLE
INFO: Not setting value for variable float u_light_ambient_w; uniform is not active.

### ISSUE THREAD

**Issue by ghoshaw** [kirumang/Pix2Pose#5]
Hi, 
    I run the lmo dataset by tools to create the xyz map, but the log says "INFO: Not setting value for variable float u_light_ambient_w; uniform is not active.", and then the code stops.  BTW, I download the train and test file in BOP for lmo, and run the tools.

**Comment by kirumang** [comment]
It seems OpenGL makes problems when you run the code in a virtual environment / a docker container / a remote server with ssh.

My suggestions are:
1) Add DISPLAY command to attach the code to the first display (if it exists),
```
DISPLAY=:0 python3 <code>
```
or, 
2) install and use xvfb to run the code in a virtual display.
```
apt-get install xvfb
xvfb-run -s "-screen 0 1400x900x24" python3 <code>
```
In my case, one of the tricks above solved GL related issues.

Especially, if you are using a docker container, 
I would recommend passing these arguments when you run the docker container, which connects the host display to the container.
```
xhost +local:root;nvidia-docker run -e DISPLAY -e QT_X11_NO_MITSHM=1
```
I hope this solves your problem.

**Comment by ghoshaw** [comment]
![image](https://user-images.githubusercontent.com/23494873/70422109-23753a80-1aa6-11ea-9939-9a519af40ce6.png)
I found that the npy file is created inlcudes the image and xyz, though the warning is still there. Is that ok?

**Comment by kirumang** [comment]
I think it is okay if it creates npy files for each object. 
I will close the issue then.
